import {
  ArrowRight,
  ArrowUpDown,
  Check,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  ExternalLink,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Plus,
  Search,
  Settings,
  SunMedium,
  Timer,
  Trash,
  Users,
} from "lucide-react";

export const Icons = {
  arrowRight: ArrowRight,
  arrowUpDown: ArrowUpDown,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboard: ClipboardList,
  clock: Clock,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  download: Download,
  externalLink: ExternalLink,
  file: File,
  fileText: FileText,
  help: HelpCircle,
  image: Image,
  laptop: Laptop,
  loader: Loader2,
  more: MoreVertical,
  moon: Moon,
  plus: Plus,
  search: Search,
  settings: Settings,
  sun: SunMedium,
  timer: Timer,
  trash: Trash,
  users: Users,
};